### ISSUE TITLE
Fix java-jdk dependencies in comp_gcc630 branch. 

### ISSUE THREAD

**Issue by nataliaratnikova** [cms-sw/cmsdist#3534]
java-jdk fails to install on SL7 build node with the following output:

```
* The action "install-external+java-jdk+1.7.0_79" was not completed successfully because Traceback (most recent call last):
File "/build/ratnik/SPACEMON-RELEASES/pkgtools/scheduler.py", line 199, in doSerial
result = commandSpec[0](*commandSpec[1:])
File "./pkgtools/cmsBuild", line 2862, in installApt
RpmInstallFailed: Failed to install package java-jdk. Reason:
error: Failed dependencies:
	libxslt.so.1(LIBXML2_1.0.11)(64bit) is needed by external+java-jdk+1.7.0_79-1-1.x86_64
	libxslt.so.1(LIBXML2_1.0.22)(64bit) is needed by external+java-jdk+1.7.0_79-1-1.x86_64
	libxslt.so.1(LIBXML2_1.0.24)(64bit) is needed by external+java-jdk+1.7.0_79-1-1.x86_64
	libxslt.so.1(LIBXML2_1.1.9)(64bit) is needed by external+java-jdk+1.7.0_79-1-1.x86_64
Reading Package Lists...
Get:1 http://cmsrep.cern.ch cmssw/comp/slc7_amd64_gcc630 external+java-jdk+1.7.0_79-1-1.slc7_amd64_gcc630.rpm
Building Dependency Tree...
The following NEW packages will be installed:
external+java-jdk+1.7.0_79
external+libxml2+2.9.1
0 upgraded, 2 newly installed, 0 removed and 0 not upgraded.
Get:2 http://cmsrep.cern.ch cmssw/comp/slc7_amd64_gcc630 external+libxml2+2.9.1-1-1.slc7_amd64_gcc630.rpm
Downloaded 146MB of archives.
After unpacking 292MB of additional disk space will be used.
Executing RPM (source /build/ratnik/SPACEMON-RELEASES/phedex-web-suite/share/cms/cmspkg/V00-00-24/rpm_env.sh slc7_amd64_gcc630; rpm -Uvh -r /build/ratnik/SPACEMON-RELEASES/phedex-web-suite --force --prefix /build/ratnik/SPACEMON-RELEASES/phedex-web-suite --ignoreos --ignorearch --oldpackage )...

* The action "final-job" was not completed successfully because The following dependencies could not complete:
build-cms+PHEDEX-webapp+1.4.0pre1
install-cms+PHEDEX-webapp+1.4.0pre1
install-external+java-jdk+1.7.0_79
* The action "install-cms+PHEDEX-webapp+1.4.0pre1" was not completed successfully because The following dependencies could not complete:
build-cms+PHEDEX-webapp+1.4.0pre1
* The action "build-cms+PHEDEX-combined-web+3-comp6" was not completed successfully because The following dependencies could not complete:
install-cms+PHEDEX-webapp+1.4.0pre1
* The action "build-cms+PHEDEX-webapp+1.4.0pre1" was not completed successfully because The following dependencies could not complete:
install-external+java-jdk+1.7.0_79
* The action "install-cms+PHEDEX-combined-web+3-comp6" was not completed successfully because The following dependencies could not complete:
build-cms+PHEDEX-combined-web+3-comp6
-bash-4.2$
```

**Comment by smuzaffar** [comment]
@nataliaratnikova , is thie resolved? should we close this?

**Comment by nataliaratnikova** [comment]
@smuzaffar , I am not aware of any official fix. We still only support slc6 architecture in PhEDEx and SpaceMon.  I'd have to check my private SL7 builds to see if there was any solution there.  Could you keep this open meanwhile until clarified?

**Comment by smuzaffar** [comment]
sure, we will keep it open. I just wanted to check if it is solved or not.
I guess you might be missing libxslt dependency in java-sdt.spec

**Comment by smuzaffar** [comment]
closing this very old issue, please open a new one if this is still an issue and needs fixing.
