### ISSUE TITLE
Jupyter does not work in PY3 IB

### ISSUE THREAD

**Issue by schneiml** [cms-sw/cmsdist#5563]
CMSSW usually ships with a Jupyter install:
```
cmsrel CMSSW_11_1_X_2020-02-17-2300
cd CMSSW_11_1_X_2020-02-17-2300
cmsenv
jupyter notebook
<works fine>
```

But, it seem that in the PY3 IB the setup is broken:
```
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/nweek-02616/slc7_amd64_gcc820/external/py2-setuptools/41.2.0-nmpfii/lib/python3.6/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/cvmfs/cms-ib.cern.ch/nweek-02616/slc7_amd64_gcc820/external/py2-setuptools/41.2.0-nmpfii/lib/python3.6/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/cvmfs/cms-ib.cern.ch/nweek-02616/slc7_amd64_gcc820/external/py2-setuptools/41.2.0-nmpfii/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (notebook 6.0.2 (/cvmfs/cms-ib.cern.ch/nweek-02616/slc7_amd64_gcc820/external/py3-notebook/6.0.2/lib/python3.6/site-packages), Requirement.parse('notebook==5.7.8'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_1_PY3_X_2020-02-17-2300/external/slc7_amd64_gcc820/bin/jupyter-notebook", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/cvmfs/cms-ib.cern.ch/nweek-02616/slc7_amd64_gcc820/external/py2-setuptools/41.2.0-nmpfii/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3250, in <module>
    @_call_aside
  File "/cvmfs/cms-ib.cern.ch/nweek-02616/slc7_amd64_gcc820/external/py2-setuptools/41.2.0-nmpfii/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/cvmfs/cms-ib.cern.ch/nweek-02616/slc7_amd64_gcc820/external/py2-setuptools/41.2.0-nmpfii/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/cvmfs/cms-ib.cern.ch/nweek-02616/slc7_amd64_gcc820/external/py2-setuptools/41.2.0-nmpfii/lib/python3.6/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/cvmfs/cms-ib.cern.ch/nweek-02616/slc7_amd64_gcc820/external/py2-setuptools/41.2.0-nmpfii/lib/python3.6/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/cvmfs/cms-ib.cern.ch/nweek-02616/slc7_amd64_gcc820/external/py2-setuptools/41.2.0-nmpfii/lib/python3.6/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'notebook==5.7.8' distribution was not found and is required by the application
```

I don't see a way to have a Python3 notebook from the normal IB either.

**Comment by davidlange6** [comment]
Likely a defect in trying to keep the binaries from two python stacks out of conflict. If you changed 5.7.8 to 6.3.0 in a local copy of the jupyter-notebook script it ought to work. Its not immediately obvious how to make a general solution fix.


On Feb 18, 2020, at 12:42 PM, Marcel Schneider <notifications@github.com<mailto:notifications@github.com>> wrote:


CMSSW usually ships with a Jupyter install:

cmsrel CMSSW_11_1_X_2020-02-17-2300
cd CMSSW_11_1_X_2020-02-17-2300
cmsenv
jupyter notebook
<works fine>


But, it seem that in the PY3 IB the setup is broken:

Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/nweek-02616/slc7_amd64_gcc820/external/py2-setuptools/41.2.0-nmpfii/lib/python3.6/site-packages/pkg_resources/__init__.py<http://cms-ib.cern.ch/nweek-02616/slc7_amd64_gcc820/external/py2-setuptools/41.2.0-nmpfii/lib/python3.6/site-packages/pkg_resources/__init__.py>", line 583, in _build_master
    ws.require(__requires__)
  File "/cvmfs/cms-ib.cern.ch/nweek-02616/slc7_amd64_gcc820/external/py2-setuptools/41.2.0-nmpfii/lib/python3.6/site-packages/pkg_resources/__init__.py<http://cms-ib.cern.ch/nweek-02616/slc7_amd64_gcc820/external/py2-setuptools/41.2.0-nmpfii/lib/python3.6/site-packages/pkg_resources/__init__.py>", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/cvmfs/cms-ib.cern.ch/nweek-02616/slc7_amd64_gcc820/external/py2-setuptools/41.2.0-nmpfii/lib/python3.6/site-packages/pkg_resources/__init__.py<http://cms-ib.cern.ch/nweek-02616/slc7_amd64_gcc820/external/py2-setuptools/41.2.0-nmpfii/lib/python3.6/site-packages/pkg_resources/__init__.py>", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (notebook 6.0.2 (/cvmfs/cms-ib.cern.ch/nweek-02616/slc7_amd64_gcc820/external/py3-notebook/6.0.2/lib/python3.6/site-packages<http://cms-ib.cern.ch/nweek-02616/slc7_amd64_gcc820/external/py3-notebook/6.0.2/lib/python3.6/site-packages>), Requirement.parse('notebook==5.7.8'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_1_PY3_X_2020-02-17-2300/external/slc7_amd64_gcc820/bin/jupyter-notebook<http://cms-ib.cern.ch/week0/slc7_amd64_gcc820/cms/cmssw/CMSSW_11_1_PY3_X_2020-02-17-2300/external/slc7_amd64_gcc820/bin/jupyter-notebook>", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/cvmfs/cms-ib.cern.ch/nweek-02616/slc7_amd64_gcc820/external/py2-setuptools/41.2.0-nmpfii/lib/python3.6/site-packages/pkg_resources/__init__.py<http://cms-ib.cern.ch/nweek-02616/slc7_amd64_gcc820/external/py2-setuptools/41.2.0-nmpfii/lib/python3.6/site-packages/pkg_resources/__init__.py>", line 3250, in <module>
    @_call_aside
  File "/cvmfs/cms-ib.cern.ch/nweek-02616/slc7_amd64_gcc820/external/py2-setuptools/41.2.0-nmpfii/lib/python3.6/site-packages/pkg_resources/__init__.py<http://cms-ib.cern.ch/nweek-02616/slc7_amd64_gcc820/external/py2-setuptools/41.2.0-nmpfii/lib/python3.6/site-packages/pkg_resources/__init__.py>", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/cvmfs/cms-ib.cern.ch/nweek-02616/slc7_amd64_gcc820/external/py2-setuptools/41.2.0-nmpfii/lib/python3.6/site-packages/pkg_resources/__init__.py<http://cms-ib.cern.ch/nweek-02616/slc7_amd64_gcc820/external/py2-setuptools/41.2.0-nmpfii/lib/python3.6/site-packages/pkg_resources/__init__.py>", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/cvmfs/cms-ib.cern.ch/nweek-02616/slc7_amd64_gcc820/external/py2-setuptools/41.2.0-nmpfii/lib/python3.6/site-packages/pkg_resources/__init__.py<http://cms-ib.cern.ch/nweek-02616/slc7_amd64_gcc820/external/py2-setuptools/41.2.0-nmpfii/lib/python3.6/site-packages/pkg_resources/__init__.py>", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/cvmfs/cms-ib.cern.ch/nweek-02616/slc7_amd64_gcc820/external/py2-setuptools/41.2.0-nmpfii/lib/python3.6/site-packages/pkg_resources/__init__.py<http://cms-ib.cern.ch/nweek-02616/slc7_amd64_gcc820/external/py2-setuptools/41.2.0-nmpfii/lib/python3.6/site-packages/pkg_resources/__init__.py>", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/cvmfs/cms-ib.cern.ch/nweek-02616/slc7_amd64_gcc820/external/py2-setuptools/41.2.0-nmpfii/lib/python3.6/site-packages/pkg_resources/__init__.py<http://cms-ib.cern.ch/nweek-02616/slc7_amd64_gcc820/external/py2-setuptools/41.2.0-nmpfii/lib/python3.6/site-packages/pkg_resources/__init__.py>", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'notebook==5.7.8' distribution was not found and is required by the application


I don't see a way to have a Python3 notebook from the normal IB either.

**Comment by schneiml** [comment]
The correct version number to use is `6.0.2 `, but that workaround works indeed. Thanks!

**Comment by davidlange6** [comment]
Ok - thanks - I think we can work around this as well - will look into it.

On Feb 18, 2020, at 2:14 PM, Marcel Schneider <notifications@github.com<mailto:notifications@github.com>> wrote:


The correct version number to use is 6.0.2 , but that workaround works indeed. Thanks!

**Comment by makortel** [comment]
assign core

**Comment by smuzaffar** [comment]
@schneiml , you need to run `jupyter notebook3` or `jupyter-notebook3` for python 3.

**Comment by schneiml** [comment]
@smuzaffar yes, I just noticed that there is indeed a `jupyter-notebook3`, and that one works. Thanks!
