### ISSUE TITLE
Bump xrootd to 5.3.x

### ISSUE THREAD

**Issue by osschar** [cms-sw/cmsdist#7179]
We are still using 4.12, it's high time to move on! :)

On a serious note, fwlite can not open CERN EOS files througg TFile::Open("root://eoscms.cern.ch/..." because of that. I assume cmsRun has the same problem.

**Comment by smuzaffar** [comment]
@osschar , we had tested 5.1.1 ( https://github.com/cms-sw/cmsdist/pull/6831 ) but could not find a way to get it work in CMSSW. I can try with 5.3 again

**Comment by osschar** [comment]
Thank you! I can help if there are changes needed in XrdAdaptor (or wherever) ... have some other things I need to fix there.

**Comment by osschar** [comment]
My (event-display development) build of root (+/- master) happily picked up system xrootd-5.2.0 (Fedora 33) and it works ok, opening CERN  EOS files with libNetxNG.so. I'm updating system xrootd to 5.3.0 and rebuilding root.

**Comment by osschar** [comment]
root master with xrootd-5.3.0 works.
Exiting root without deleting TNetXNGFile object causes SEGV (calling just Close() is not good enough, eihter).
```
0x00007ffff74b1a66 in pthread_rwlock_rdlock () from /lib64/libpthread.so.0
(gdb) bt
#0  0x00007ffff74b1a66 in pthread_rwlock_rdlock () from /lib64/libpthread.so.0
#1  0x00007fffe91ecd62 in XrdCl::Env::GetInt(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int&) ()
   from /lib64/libXrdCl.so.3
#2  0x00007fffe9207a39 in XrdCl::PostMaster::PostMaster() () from /lib64/libXrdCl.so.3
#3  0x00007fffe91fed5e in XrdCl::DefaultEnv::GetPostMaster() () from /lib64/libXrdCl.so.3
#4  0x00007fffe9245fc5 in XrdCl::FileStateHandler::~FileStateHandler() () from /lib64/libXrdCl.so.3
#5  0x00007fffe9243bd0 in XrdCl::File::~File() () from /lib64/libXrdCl.so.3
#6  0x00007fffe9243c6d in XrdCl::File::~File() () from /lib64/libXrdCl.so.3
#7  0x00007fffef69630f in TNetXNGFile::~TNetXNGFile (this=0x2019f20, __in_chrg=<optimized out>)
    at /home/matevz/root-dev/dev-1/net/netxng/src/TNetXNGFile.cxx:233
#8  0x00007fffef696396 in TNetXNGFile::~TNetXNGFile (this=0x2019f20, __in_chrg=<optimized out>)
    at /home/matevz/root-dev/dev-1/net/netxng/src/TNetXNGFile.cxx:236
#9  0x00007ffff7bc5ad3 in TCollection::GarbageCollect (obj=0x2019f20) at /home/matevz/root-dev/dev-1/core/cont/src/TCollection.cxx:736
#10 0x00007ffff7bcdbe5 in TList::Delete (this=0x4307c0, option=0x7ffff7e1726b "slow") at /home/matevz/root-dev/dev-1/core/cont/src/TList.cxx:508
#11 0x00007ffff7af756b in TROOT::~TROOT (this=0x7ffff7f5a900 <ROOT::Internal::GetROOT1()::alloc>, __in_chrg=<optimized out>)
    at /home/matevz/root-dev/dev-1/core/base/src/TROOT.cxx:889
#12 0x00007ffff7af4f5f in at_exit_of_TROOT () at /home/matevz/root-dev/dev-1/core/base/src/TROOT.cxx:290
#13 0x00007ffff7317247 in __run_exit_handlers () from /lib64/libc.so.6
#14 0x00007ffff73173f0 in exit () from /lib64/libc.so.6
#15 0x00007ffff7c91627 in TUnixSystem::Exit (this=0x42a800, code=0, mode=true) at /home/matevz/root-dev/dev-1/core/unix/src/TUnixSystem.cxx:2157
#16 0x00007ffff7b0cc16 in TApplication::Terminate (this=0x482000, status=0) at /home/matevz/root-dev/dev-1/core/base/src/TApplication.cxx:1672
#17 0x00007ffff7facf9d in TRint::Terminate (this=0x482000, status=0) at /home/matevz/root-dev/dev-1/core/rint/src/TRint.cxx:696
#18 0x00007ffff7b0b37d in TApplication::ProcessLine (this=0x482000, line=0x7fffffffb589 ".q", sync=false, err=0x7fffffffb51c)
    at /home/matevz/root-dev/dev-1/core/base/src/TApplication.cxx:1334
#19 0x00007ffff7fad334 in TRint::ProcessLineNr (this=0x482000, filestem=0x7ffff7fbd6cf "ROOT_prompt_", line=0x7fffffffb589 ".q", error=0x7fffffffb51c)
    at /home/matevz/root-dev/dev-1/core/rint/src/TRint.cxx:766
#20 0x00007ffff7facab4 in TRint::HandleTermInput (this=0x482000) at /home/matevz/root-dev/dev-1/core/rint/src/TRint.cxx:612
#21 0x00007ffff7faa5c5 in TTermInputHandler::Notify (this=0x1381dc0) at /home/matevz/root-dev/dev-1/core/rint/src/TRint.cxx:132
#22 0x00007ffff7fae98f in TTermInputHandler::ReadNotify (this=0x1381dc0) at /home/matevz/root-dev/dev-1/core/rint/src/TRint.cxx:124
#23 0x00007ffff7c8fa8a in TUnixSystem::CheckDescriptors (this=0x42a800) at /home/matevz/root-dev/dev-1/core/unix/src/TUnixSystem.cxx:1322
#24 0x00007ffff7c8eec6 in TUnixSystem::DispatchOneEvent (this=0x42a800, pendingOnly=false)
    at /home/matevz/root-dev/dev-1/core/unix/src/TUnixSystem.cxx:1077
#25 0x00007ffff7b7e773 in TSystem::InnerLoop (this=0x42a800) at /home/matevz/root-dev/dev-1/core/base/src/TSystem.cxx:406
#26 0x00007ffff7b7e519 in TSystem::Run (this=0x42a800) at /home/matevz/root-dev/dev-1/core/base/src/TSystem.cxx:356
#27 0x00007ffff7b0c963 in TApplication::Run (this=0x482000, retrn=false) at /home/matevz/root-dev/dev-1/core/base/src/TApplication.cxx:1604
#28 0x00007ffff7fabddd in TRint::Run (this=0x482000, retrn=false) at /home/matevz/root-dev/dev-1/core/rint/src/TRint.cxx:463
#29 0x00000000004011e8 in main (argc=1, argv=0x7fffffffda28) at /home/matevz/root-dev/dev-1/main/src/rmain.cxx:30
```
I'll make bug reports at root and xrootd gits.

**Comment by osschar** [comment]
root: https://github.com/root-project/root/issues/8767
xrootd: https://github.com/xrootd/xrootd/issues/1487
